# https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#adding-an-action-from-the-same-repository
runs:
  using: composite
  # name: Update submodules
  # author: willhuang1997
  # description: "`git submodule update --remote` checks out the submodule repo's
  #           HEAD (as opposed to whatever commit is specified in the
  #           submodule). We want to ensure we're always testing against
  #           the most recent commit in our component-template repo."
  steps:
    - name: "update submodules"
      run: |
        python --version
        git submodule init
        git submodule update --remote
      shell: bash -l {0}