version: '3.7'
services:
  streamlit:
    image: streamlit_circleci
    build: .
    volumes:
      - type: bind
        source: ./examples
        target: /home/circleci/repo/examples
      - type: bind
        source: ./frontend/cypress
        target: /home/circleci/repo/frontend/cypress
      - type: bind
        source: ./frontend/mochawesome-report
        target: /home/circleci/repo/frontend/mochawesome-report
      - type: bind
        source: ./frontend/src
        target: /home/circleci/repo/frontend/src
      - type: bind
        source: ./lib/streamlit
        target: /home/circleci/repo/lib/streamlit
      - type: volume
        source: hard_source_webpack_plugin_cache
        target: /home/circleci/repo/frontend/node_modules/.cache/hard-source
        volume:
          nocopy: true

    networks:
      - streamlit_app

volumes:
  hard_source_webpack_plugin_cache:

networks:
  streamlit_app:

# TODO
# clean up Dockerfile, remove apt-cache, bundle run commands, etc
# multi stage builds
# regenerate all snapshots and lower threshold

# -

# how much to mount versus copy in, when do we expect changes to get picked up without having to rebuild?
# should docker/compose build and run commands go in makefile?
# docker and compose file location.. cypress/circleci sub directory?
# copy makefile in to use make commands or just use raw commands?

# --

# testing a single example
# - need to open multiple terminals, yarn start, streamlit run, yarn cy:run
# - https://stackoverflow.com/questions/39794509/how-to-open-multiple-terminals-in-docker
