name: "Set GIT_TAG env variables"

inputs:
  tag_name:
    description: 'Name of the tag'

runs:
  using: composite
  steps:
    - name: Set GIT_TAG
      env:
        GIT_TAG: ${{ inputs.tag_name }}
      run: echo 'GIT_TAG="$GIT_TAG"' >> $GITHUB_ENV
      shell: bash -ileo pipefail {0}