# https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#adding-an-action-from-the-same-repository
runs:
  using: composite
  steps:
    - name: "Install NVM, Node.js, and Yarn"
      run: |
        if [ ! -d ~/.nvm ] ; then
          # install nodejs via nvm
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.2/install.sh | bash
          source "$HOME/.nvm/nvm.sh"
          nvm install --lts=gallium
          # install yarn
          npm install -g yarn
        fi
        if [ ! -d frontend/node_modules ] ; then
          source "$HOME/.nvm/nvm.sh"
          make react-init
        fi
        echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
        echo 'source "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      shell: bash
    - name: Install pyodbc dependencies
      run: |
        ${SUDO} apt-get install -y unixodbc-dev
      shell: bash
    - name: Install graphviz dependencies
      run: |
        ${SUDO} apt update
        ${SUDO} apt-get install -y libgvc6
      shell: bash