name: Cypress Tests
on: [push]
jobs:
  checkout:
    env:
      SUDO: 'sudo'
      BASH_ENV: $HOME/.bash_profile
    runs-on: ubuntu-latest
    container: circleci/python:3.7.11
    steps:
      # This Docker file changes sets USER to circleci instead of using the default user, so we need to update file permissions for this image to work on GH Actions.
      # See https://docs.github.com/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: Checkout Streamlit code
        uses: actions/checkout@v3
      - uses: ./.github/actions/update_submodules
      - uses: ./.github/actions/premake
      - uses: ./.github/actions/make_init
      - name: Run make develop
        run: |
          make develop
        shell: bash -l -v -e -u -o pipefail {0}
      - name: Install Cypress dependencies
        run: |
          ${SUDO} apt-get install -y xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 jq curl
        shell: bash -l -v -e -u -o pipefail {0}
      - name: Init config
        run: |
          mkdir ~/.streamlit
          MAPBOX_TOKEN=$(curl -sS https://data.streamlit.io/tokens.json | jq -r '.["mapbox-localhost"]')
          echo '[mapbox]' >  ~/.streamlit/config.toml
          echo 'token = "'$MAPBOX_TOKEN'"' >> ~/.streamlit/config.toml
        shell: bash -l -v -e -u -o pipefail {0}
      - name: Init credentials
        run: |
          echo '[general]' >  ~/.streamlit/credentials.toml
          echo 'email = "test@streamlit.io"' >> ~/.streamlit/credentials.toml
        shell: bash -l -v -e -u -o pipefail {0}
      - name: Cypress Tests
        run: |
          cd frontend
          ../scripts/run_e2e_tests.py -a -f
        shell: bash -l -v -e -u -o pipefail {0}
