name: Javascript Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SUDO: 'sudo'
      BASH_ENV: $HOME/.bash_profile

    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: ./.github/actions/update_submodules
      - uses: ./.github/actions/premake
      - uses: ./.github/actions/make_init
      - name: Run make jstest
        run: |
          make jstest
