# name: Create Nightly Tag

# on:
#   schedule:
#     # Run job at 10.30pm PST or 11.30pm PDT
#     - cron:  '30 6 * * *'

# jobs:
#   create-nightly-tag:
#     runs-on: ubuntu-latest

#     permissions:
#       actions: read

#     defaults:
#       run:
#         shell: bash -ileo pipefail {0}

#     steps:
#       - name: Checkout Streamlit code
#         uses: actions/checkout@v3
#         with: 
#           persist-credentials: false
#           submodules: 'recursive'
#       - name: Set up Python 3.10
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"
#       - name: Setup virtual env
#         uses: ./.github/actions/make_init
#       - name: Run make develop
#         run: make develop
#       # TODO: Refactor?
#       - name: Create tag
#         run: |
#           git config user.email "core+streamlitbot-github@streamlit.io"
#           git config user.name "Streamlit Bot"

#           TAG="$(./scripts/pypi_nightly_create_tag.py)"

#           ./scripts/update_version.py $TAG
#           ./scripts/update_name.py streamlit-nightly

#           git add lib/setup.py
#           git add frontend/package.json

#           git add lib/streamlit/__init__.py
#           git add lib/streamlit/version.py

#           git commit -m "Update version and project name in files"

#           git tag -a $TAG -m "Streamlit nightly $TAG"
#           git push origin $TAG


# # Check is the last commit is still pending
# gh api \
#   -H "Accept: application/vnd.github+json" \
#   /repos/streamlit/streamlit/commits/gitMigration/status

# gh api \
#   -H "Accept: application/vnd.github+json" \
#   /repos/streamlit/streamlit/commits/gitMigration

# # Check the tagged branch for specified tests passing
# gh api \
#   -H "Accept: application/vnd.github+json" \
#   /repos/streamlit/streamlit/commits/gitMigration/check-runs?check_name="python-prod-deps-smoke-test"&filter="latest"
# gh api \
#   -H "Accept: application/vnd.github+json" \
#   /repos/streamlit/streamlit/commits/gitMigration/check-runs?check_name="python_tests+(3.7)"&filter="latest"
# gh api \
#   -H "Accept: application/vnd.github+json" \
#   /repos/streamlit/streamlit/commits/gitMigration/check-runs?check_name="python_tests+(3.10)"&filter="latest"
# gh api \
#   -H "Accept: application/vnd.github+json" \
#   /repos/streamlit/streamlit/commits/gitMigration/check-runs?check_name="js_tests"&filter="latest"

# # show all tests on latest commit
# gh api \
#   -H "Accept: application/vnd.github+json" \
#   /repos/streamlit/streamlit/commits/git-cypress/check-runs?filter="latest"


# # gh api \
# #   -H "Accept: application/vnd.github+json" \
# #   /repos/OWNER/REPO/check-suites/CHECK_SUITE_ID/check-runs

# gh api \
#   -H "Accept: application/vnd.github+json" \
#   /repos/streamlit/streamlit/check-suites/7934021524/check-runs

# #  "name": "Dependabot" (IGNORE)
# # 7934021330

# # "name": "Cypress", (IGNORE)
# # 7934021340

# # "name": "GitHub Actions" (cli-regression-test),
# # 7934021518

# # "name": "GitHub Actions" (python-prod-deps-smoke-test),
# # 7934021522

# # "name": "GitHub Actions" (js_tests),
# # 7934021523

# # "name": "GitHub Actions" (python-tests),
# # 7934021524

# gh api \
#   -H "Accept: application/vnd.github+json" \
#   /repos/streamlit/streamlit/commits/gitMigration/status


# gh api \
#   -H "Accept: application/vnd.github+json" \
#   /repos/streamlit/streamlit/check-suites/7934021524