name: python-max-version
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    # container: circleci/python:3.10.0
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: ./.github/actions/update_submodules
