name: python-max-version
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    container: circleci/python:3.10.0
    steps:
      # This Docker file changes sets USER to circleci instead of using the default user, so we need to update file permissions for this image to work on GH Actions.
      # See https://docs.github.com/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - name: Checkout Streamlit code
        uses: actions/checkout@v3
      # cache: 'yarn'
      - name: change to lib dir
        run: cd lib
        shell: bash
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv' # caching pipenv dependencies
      - uses: ./.github/actions/update_submodules
        env:
          SUDO: 'sudo'
      - uses: ./.github/actions/make_init
        env:
          SUDO: 'sudo'
      - name: change back dir
        run: cd ..
        shell: bash
    