name: Test Slack Messaging

on:
  push:
    branches:
    - 'add-link'

jobs:
  slack:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash --login -eo pipefail {0}

    steps:
      - name: Checkout Streamlit code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Test Nightly Slack Message
        env:
          SLACK_WEBHOOK: ${{ secrets.TEST_WEBHOOK }}
          RUN_ID: ${{ github.run_id }}
        run: python scripts/slack_notifications.py nightly build